### ISSUE TITLE
Torpedoes

### ISSUE THREAD

**Issue by ethanhowell** [ethanhowell/jsmotion#5]
Add the capability to shoot torpedoes when `w` or `i` is pressed

**Comment by pv2k** [comment]
Can I work on this one???😃😃

**Comment by ethanhowell** [comment]
Sure.  Just fork it before you start and make a branch called collision detection

**Comment by pv2k** [comment]
When 'w' or 'i' is pressed, what exactly should happen???

**Comment by ethanhowell** [comment]
A new div with class `torpedo` should be created. That element needs to be passed to a constructor that constructs a `torpedo` object with the following fields: `element, width, height, x, y, vx, vy, ax, ay, gravity Acceleration, sqrdDistToWormhole, age, parentStarship`, as well as object constants `lifetime, speedIncrease`. The torpedoes' `x` and `y` need to be the same as the ship it fired from (the `parentStarship`), but its `vx` and `vy` needs to be the `parentStarship`'s velocities plus `speedIncrease`, which should be set to `.5` (arbitrary number, will change later). Thanks for your help!

**Comment by pv2k** [comment]
Okay. This sounds complicated :sweat_smile:

**Comment by ethanhowell** [comment]
Yeah it’s pretty complicated. You don’t have to work on it if you don’t want to, it’s your choice. There might be some other simpler ones to help with on GitHub if you want, you just have to keep searching. Happy Coding!!!
