### ISSUE TITLE
Objects

### ISSUE THREAD

**Issue by ethanhowell** [ethanhowell/jsmotion#6]
Make `physicsbody` an object, with sub-objects including spaceships and torpedoes

**Comment by Occult-Dev** [comment]
Hey, I wouldn't mind taking a crack at this.

Just a few things:
- Do you want `physicsbody` to be global, or attached to something else in the script?
- When you say that it's sub-object should be _spaceship_, just to be clear, are you referring to what's labled at '_starship_' in the code, or something else?
- Anything else I should know [ _like, what `spaceships` and `torpedoes` should hold, or should they just be blank sub-objects_ ]

**Comment by ethanhowell** [comment]
@StuffBySpencer Ok. Somebody else is working on the torpedo functionality, but the physics still need to be there. Here is what needs to happen:
- [x] The `physicsbody` class needs to have the following fields: `element, width, height, x, y, vx, vy, ax, ay, gravity Acceleration, sqrdDistToWormhole`, as well as the function `physicsEngine`
- [x] The spaceship/`starship` subclass needs to have, in addition to those properties, `isWarping, userHasControl, engineAcceleration, gravityAcceleration, theta, omega, rx, ry`, as well as the following functions: `warp, getWarpPosition`
- [x] The `torpedo` subclass, in addition to the fields that `physicsbody` has, needs to have constants `lifetime, speedIncrease` as well as variable `age, parentStarship`.  The torpedo functions haven't been added yet, so those will come later

Thanks for your help!

**Comment by Occult-Dev** [comment]
Alright, just submitted the PR, let me know if anything needs changing! :)
[ _I'm new at all of this, so sorry if I messed something up_ ]

**Comment by ethanhowell** [comment]
@StuffBySpencer Alright, I'll take a look at it and let you know what I think. Thanks for your help!

**Comment by ethanhowell** [comment]
Merged. Thanks again 👍
